import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {KANTO,hasCoordinates,filterBuildings,normalize,escapeHtml,safeUrl,distanceMeters,duplicateCoordinates,articleHtml} from '../assets/core.mjs';
import {validate} from '../scripts/validate-data.mjs';
const data=JSON.parse(await readFile(new URL('../data/buildings.json',import.meta.url),'utf8'));
test('published dataset passes validation',()=>assert.deepEqual(validate(data).errors,[]));
test('all seven Kanto prefectures represented',()=>assert.deepEqual(new Set(data.map(b=>b.prefecture).filter(p=>KANTO.includes(p))),new Set(KANTO)));
test('undefined, null, strings, non-finite and out-of-Japan coordinates excluded',()=>{
  for(const b of [undefined,null,{}, {lat:'35.7',lng:139.7},{lat:NaN,lng:139.7},{lat:35,lng:Infinity},{lat:0,lng:0},{lat:35,lng:139,location:{status:'withheld'}}])assert.equal(hasCoordinates(b),false);
  assert.equal(hasCoordinates({lat:35,lng:139}),true);
});
test('normalization supports width, kana, case',()=>assert.equal(normalize('ＡＢＣ ｶﾞﾗｽ'),normalize('abc がらす')));
test('multiple search terms are ANDed',()=>{const result=filterBuildings(data,{query:'東京 美術館'});assert(result.length>0);assert(result.every(b=>b.prefecture==='東京都'&&b.buildingTypes.includes('美術館')));});
test('region, architect and use can be combined',()=>assert.equal(filterBuildings(data,{region:'群馬県',architect:'磯崎新',type:'美術館'}).length,1));
test('empty result is not silently relaxed',()=>assert.equal(filterBuildings(data,{region:'神奈川県',architect:'隈研吾'}).length,0));
test('oldest and newest use completion year',()=>{const old=filterBuildings(data,{sort:'oldest'}),recent=filterBuildings(data,{sort:'newest'});assert.equal(old[0].completionYear,1896);assert.equal(recent[0].completionYear,2010);});
test('no mutated shared data during sort',()=>{const ids=data.map(b=>b.id);filterBuildings(data,{sort:'oldest'});assert.deepEqual(data.map(b=>b.id),ids);});
test('thirty colocated buildings are not deduplicated',()=>{const many=Array.from({length:30},(_,i)=>({...data[0],id:`same-${i}`}));assert.equal(filterBuildings(many).filter(hasCoordinates).length,30);assert.equal(duplicateCoordinates(many)[0].ids.length,30);});
test('dataset has no exact coordinate duplicates',()=>assert.deepEqual(duplicateCoordinates(data),[]));
test('haversine distance has proper magnitude and symmetry',()=>{assert.equal(distanceMeters(data[0],data[0]),0);assert(Math.abs(distanceMeters({lat:0,lng:0},{lat:0,lng:1})-111195)<2);assert.equal(distanceMeters(data[0],data[1]),distanceMeters(data[1],data[0]));});
test('text and source URLs are escaped',()=>{assert.equal(escapeHtml('<img "\'&>'),'&lt;img &quot;&#39;&amp;&gt;');assert.equal(safeUrl('javascript:alert(1)'), '');assert.equal(safeUrl('data:text/html,hello'), '');assert.equal(safeUrl('https://example.org'),'https://example.org/');});
test('article explicitly distinguishes unverified entrance coordinates',()=>{const html=articleHtml(data[0],data);assert.match(html,/施設座標（入口未照合）/);assert.match(html,/全項目の検証完了を意味しません/);assert.match(html,/現地入口と建物輪郭/);});
test('article IDs resolve and no inline event handlers',()=>{for(const b of data){const html=articleHtml(b,data);for(const match of html.matchAll(/href="#(source-\d+)"/g))assert(html.includes(`id="${match[1]}"`));assert(!/\son\w+=/.test(html));assert.equal((html.match(/<h1>/g)||[]).length,1);}});
test('malicious dataset text cannot inject HTML or source javascript',()=>{const b=structuredClone(data[0]);b.nameJa='<script>alert(1)</script>';b.sources[0].url='javascript:alert(1)';const html=articleHtml(b,data);assert(!html.includes('<script>'));assert(!html.includes('href="javascript:'));});
test('nested static article links use root prefix',()=>{const html=articleHtml(data[0],data,'../');assert.match(html,/href="\.\.\/\?building=/);assert.match(html,/href="\.\.\/building.html\?id=/);});
test('unknown source references fail validation',()=>{const d=structuredClone(data);d[0].components[0].sourceIds=['missing'];assert(validate(d).errors.some(x=>x.includes('missing')));});
test('duplicate ID and slug fail validation',()=>assert(validate([data[0],data[0]]).errors.some(x=>x.includes('重複'))));
test('the 2026 roof material is not silently described as original cedar',()=>{const b=data.find(x=>x.id==='bato-hiroshige');assert(b.components.some(x=>x.part.includes('2026')&&x.material.includes('アルミ')));assert(b.components.some(x=>x.part.includes('創建時')&&x.material==='杉'));});
