"""Offline Chromium DOM checks; no navigation or external network.
The production HTML/CSS and JS are loaded from local files into a blank page.
Leaflet, fetch, and URL history are explicit test fixtures, not an end-to-end test.
"""
import json, re, os
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT.parent/'qa'; OUT.mkdir(exist_ok=True)
DATA=json.loads((ROOT/'data/buildings.json').read_text())
CSS=(ROOT/'assets/styles.css').read_text()+'\n'+(ROOT/'assets/refinements.css').read_text()
STUB=(ROOT/'tests/leaflet-stub.js').read_text()
LOC=(ROOT/'assets/location.mjs').read_text().replace('export ', '')
CORE=re.sub(r'^import .*?;\n','',(ROOT/'assets/core.mjs').read_text(),flags=re.M).replace('export ', '')
APP='const e=escapeHtml;\n'+re.sub(r'^import .*?;\n','',(ROOT/'assets/app.js').read_text(),flags=re.M)
APP=APP.replace('location.href', "'https://architecture.invalid/'").replace('location.search',"''")
APP=APP.replace("history.replaceState(null,'',u)","window.__testUrl=u.href")
checks=[]
def check(label,condition):
    assert condition,label
    checks.append(label)
def render(page,path):
    html=(ROOT/path).read_text()
    html=re.sub(r'<script\b[^>]*>[\s\S]*?</script>','',html)
    html=re.sub(r'<link\b[^>]*>','',html)
    html=html.replace('</head>',f'<style>{CSS}</style></head>')
    page.set_content(html,wait_until='domcontentloaded')
def app(page,fixture=True,data=None):
    render(page,'index.html')
    if fixture:page.add_script_tag(content=STUB)
    payload=json.dumps(data if data is not None else DATA,ensure_ascii=False)
    page.add_script_tag(content='(()=>{const fetch=async()=>({ok:true,json:async()=>('+payload+')});\n'+LOC+'\n'+CORE+'\n'+APP+'\n})();')
    page.wait_for_function(f"document.querySelectorAll('.building-card').length==={len(data if data is not None else DATA)}")
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),args=['--no-sandbox'])
    page=browser.new_page(viewport={'width':1440,'height':1000},reduced_motion='reduce')
    errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
    app(page)
    check(f'{len(DATA)} markers created independently',page.locator('.leaflet-marker-icon').count()==len(DATA))
    coords=page.evaluate('window.__mapFixture.markers.map(m=>m.coords)')
    check('marker coordinates unchanged from dataset',sorted(coords)==sorted([[b['lat'],b['lng']] for b in DATA]))
    check('no year/count numbers in markers',all(not t.strip() for t in page.locator('.leaflet-marker-icon').all_text_contents()))
    page.locator('#search-input').fill('磯崎新');page.wait_for_function("document.querySelectorAll('.building-card').length===2")
    check('search filters list and map together',page.locator('.leaflet-marker-icon').count()==2)
    page.locator('#region-filter').select_option('群馬県');page.wait_for_function("document.querySelectorAll('.building-card').length===1")
    check('combined search and region yield correct record','群馬県立近代美術館' in page.locator('.building-card').inner_text())
    page.locator('#search-input').fill('not-a-building');page.wait_for_selector('#empty-reset')
    check('zero results have a recovery action',page.locator('#empty-reset').is_visible())
    page.locator('#empty-reset').click();page.wait_for_function(f"document.querySelectorAll('.building-card').length==={len(DATA)}")
    page.locator('.building-card').first.hover()
    page.locator('#more-filters').click()
    page.locator('#sort-filter').select_option('oldest')
    check('hover preview does not change selected-building URL', 'building=' not in page.evaluate('window.__testUrl'))
    page.locator('[data-map="nmwa-main-building"]').click()
    check('map action requests zoom 17',page.evaluate('window.__mapFixture.zoom')==17)
    check('map action saves building ID in URL parameters','building=nmwa-main-building' in page.evaluate('window.__testUrl'))
    check('zoom requests persistent building-name labels',page.evaluate('window.__mapFixture.markers.every(m=>m.tooltip.opts.permanent)'))
    page.evaluate('window.__tileError()')
    check('tile-error handler keeps all markers and displays warning','背景地図を取得できません' in page.locator('#map-note').inner_text() and page.locator('.leaflet-marker-icon').count()==len(DATA))
    check('1440px split view has no horizontal overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    check('application code has no uncaught JS exceptions',not errors)
    many=[dict(DATA[0],id=f'test-{i}',slug=f'test-{i}',nameJa=f'テスト建築 {i}') for i in range(30)]
    bulk=browser.new_page(viewport={'width':1440,'height':1000},reduced_motion='reduce');app(bulk,data=many)
    bulk.locator('.leaflet-marker-icon').last.click()
    check('30 overlapping coordinates retain 30 selectable buildings',bulk.locator('[data-pick]').count()==30)
    bulk.locator('[data-pick="test-29"]').focus()
    bulk.keyboard.press('Escape')
    check('Escape dismisses overlap picker and restores marker focus',bulk.locator('#overlap-picker').is_hidden() and bulk.locator('.leaflet-marker-icon').last.evaluate('(e)=>e===document.activeElement'))
    bulk.locator('.leaflet-marker-icon').last.click()
    bulk.locator('[data-pick="test-29"]').click()
    check('overlap picker selects the requested building','テスト建築 29' in bulk.locator('.leaflet-popup').inner_text())
    check('overlap selection never moves source coordinates',bulk.evaluate('window.__mapFixture.markers.every(m=>m.coords[0]===35.71556&&m.coords[1]===139.77583)'))
    if page.locator('#extra-filters').is_hidden(): page.locator('#more-filters').click()
    page.locator('#visit-filter').select_option('closed')
    check('closed-building filter shows Tokyo Bunka only', page.locator('.building-card').count()==1 and '東京文化会館' in page.locator('.building-card').inner_text())
    check('closed-building card has visible restriction badge',page.locator('.closed-badge').is_visible())
    # URLs are checked against generated output; no network navigation is attempted.
    for width in (1440,768,390,320):
        phone=browser.new_page(viewport={'width':width,'height':900},reduced_motion='reduce');app(phone,fixture=False)
        check(f'{width}px map-unavailable fallback shows the list',phone.locator('.results-panel').is_visible())
        check(f'{width}px index has no horizontal overflow',phone.evaluate('document.documentElement.scrollWidth<=innerWidth'))
        links=phone.locator('.building-card h2 a').evaluate_all('(links)=>links.map(a=>a.getAttribute("href"))')
        check(f'{width}px all building links resolve to local articles',all((ROOT/link).is_file() for link in links))
        if width in (1440,390):phone.screenshot(path=str(OUT/f'list-{width}.png'),full_page=True)
        render(phone,links[0])
        check(f'{width}px static article has correct sections',phone.locator('#sources').count()==1 and phone.locator('#materials').count()==1)
        check(f'{width}px article has no horizontal overflow',phone.evaluate('document.documentElement.scrollWidth<=innerWidth'))
        if width==1440:check('desktop article reading column is at most 820px',phone.locator('.article-page').bounding_box()['width']<=820)
        if width==390:phone.screenshot(path=str(OUT/'article-mobile.png'),full_page=True)
        phone.close()
    nojs=browser.new_context(java_script_enabled=False,viewport={'width':390,'height':900})
    article=nojs.new_page();render(article,'catalogue.html')
    check('no-JavaScript catalogue contains every building',article.locator('a[href^="articles/"]').count()==len(DATA))
    render(article,'articles/bato-hiroshige-museum.html')
    check('no-JavaScriptScript article has original and current material sections',article.locator('details.component').count()==2)
    article.locator('details.component').last.locator('summary').click()
    check('native material disclosure works without JavaScript','35種類' in article.locator('details.component').last.inner_text())
    check('article reference target exists',article.locator('#source-1').count()==1)
    article.screenshot(path=str(OUT/'bato-nojs.png'),full_page=True)
    render(article,'articles/tokyo-bunka-kaikan.html')
    check('closure notice is present without JavaScript',article.locator('.visit-alert').is_visible())
    article.screenshot(path=str(OUT/'bunka-nojs.png'),full_page=True)
    browser.close()
report={'date':'2026-09-14','passed':len(checks),'checks':checks,'method':'In-memory Chromium DOM: production HTML/CSS/JS with declared Leaflet/fetch/history fixtures','limitations':['No live Leaflet/OSM rendering or HTTP navigation verification; browser navigation is restricted in this environment.','No Safari or physical iPhone test.','These tests check behavior and layout, not geographic truth.']}
(OUT/'dom-report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(report,ensure_ascii=False,indent=2))
